# Generated by Django 5.2.3 on 2025-07-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dealer_initiatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField()),
                ('dealer_account_type', models.CharField(max_length=50)),
                ('deale_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('message', models.TextField()),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('comments', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='dealer_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField()),
                ('dealer_account_type', models.CharField(max_length=50)),
                ('deale_name', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('rate_count', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='reach_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField()),
                ('dealer_account_type', models.CharField(max_length=50)),
                ('deale_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=70)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='schedule_pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField()),
                ('dealer_account_type', models.CharField(max_length=50)),
                ('deale_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=70)),
                ('pincode', models.CharField(max_length=50)),
                ('state_n_country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('select_date', models.DateField()),
                ('select_time', models.TimeField()),
            ],
        ),
    ]
