# Generated by Django 5.2.3 on 2025-07-15 06:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DGKabadiTechno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kt_id', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('aadhar_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(0)])),
                ('aadhar_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=12)),
                ('ProfilePic', models.ImageField(blank=True, default='photos/Profile_Pic.png', null=True, upload_to='DGKT/ProfilePic')),
                ('DGLogo', models.ImageField(default='photos/Profile_Pic.png', upload_to='DGKT/DGLogo')),
                ('DGLogoWoBg', models.ImageField(default='photos/Profile_Pic.png', upload_to='DGKT/DGLogoWoBg')),
                ('otp', models.CharField(default='000000', max_length=7)),
                ('DGPin', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'active'), ('unactive', 'unactive')], default='unactive', max_length=12)),
            ],
            options={
                'verbose_name': 'DG Kabadi Techno',
                'verbose_name_plural': 'DG Kabadi Techno',
            },
        ),
        migrations.CreateModel(
            name='DGDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kt_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('DGid', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.CharField(max_length=80, null=True)),
                ('qr_image', models.ImageField(null=True, upload_to='DGKT/qrcodes')),
                ('document', models.FileField(blank=True, null=True, upload_to='DGKT/documents', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('document_hash_value', models.CharField(max_length=255, null=True)),
                ('DGkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DGKT.dgkabaditechno')),
            ],
            options={
                'verbose_name': 'DG Detail',
                'verbose_name_plural': 'DG Details',
            },
        ),
    ]
