# Generated by Django 5.2.3 on 2025-07-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dealer_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250, null=True)),
                ('dealer_id', models.IntegerField()),
                ('subcategory_name', models.CharField(max_length=250)),
                ('subcategory_image', models.ImageField(blank=True, upload_to='photos/SubCategory')),
                ('GST', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('pcs', 'pcs')], max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile')),
                ('price_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer_details.pricelist')),
            ],
        ),
    ]
