# Generated by Django 5.2.3 on 2025-07-15 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Cancel', 'Cancel')], default='False', max_length=20)),
                ('cart_item_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_no_1', to='carts.cartitem')),
                ('cart_item_10', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_no_10', to='carts.cartitem')),
                ('cart_item_2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_no_2', to='carts.cartitem')),
                ('cart_item_3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_no_3', to='carts.cartitem')),
                ('cart_item_4', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_no_4', to='carts.cartitem')),
                ('cart_item_5', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_no_5', to='carts.cartitem')),
                ('cart_item_6', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_no_6', to='carts.cartitem')),
                ('cart_item_7', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_no_7', to='carts.cartitem')),
                ('cart_item_8', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_no_8', to='carts.cartitem')),
                ('cart_item_9', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_no_9', to='carts.cartitem')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile')),
                ('dealer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.dealerprofile')),
            ],
        ),
    ]
