# Generated by Django 5.2.3 on 2025-07-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('carts', '0002_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='dealer_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.dealerprofile'),
        ),
    ]
