# Generated by Django 5.2.3 on 2025-07-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kt_id', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=240, null=True)),
                ('qrCode', models.ImageField(default='cvm_qrcodes/4.jpg', upload_to='marketplace/QRs')),
                ('end_duration', models.DateField(null=True)),
                ('duration_active', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='deactive', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.dealerprofile')),
            ],
        ),
    ]
