# Generated by Django 5.2.3 on 2025-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/QRs'),
        ),
    ]
