# Generated by Django 5.2.3 on 2025-07-15 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Dealer', 'Dealer')], max_length=30, null=True)),
                ('account_role', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_line1', models.CharField(max_length=200, verbose_name='Address Line 1')),
                ('add_line2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('landmark', models.CharField(blank=True, max_length=100, verbose_name='Landmark')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('zipcode', models.IntegerField(verbose_name='Zipcode')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Address')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kt_id', models.CharField(editable=False, max_length=20, verbose_name='KT ID')),
                ('profile_type', models.CharField(choices=[('Personal', 'Personal'), ('Organization', 'Organization')], default='Personal', max_length=20)),
                ('ProfilePic', models.ImageField(upload_to='media/accounts/Customer/')),
                ('qrCode', models.ImageField(default='cvm_qrcodes/4.jpg', upload_to='media/accounts/Customer/QRs')),
                ('auth_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': "Customer's Profile",
            },
        ),
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kt_id', models.CharField(editable=False, max_length=20, verbose_name='KT ID')),
                ('profile_type', models.CharField(choices=[('Kabadi', 'Kabadi'), ('Collector', 'Collector'), ('Recycler', 'Recycler')], default='Kabadi', max_length=20)),
                ('qrCode', models.ImageField(default='cvm_qrcodes/4.jpg', upload_to='accounts/Dealer/QRs')),
                ('ProfilePic', models.ImageField(blank=True, default='photos/Profile_Pic.png', null=True, upload_to='accounts/Dealer/ProfilePic')),
                ('auth_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealer Profile',
                'verbose_name_plural': "Dealer's Profile",
            },
        ),
    ]
