# Generated by Django 5.2.3 on 2025-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='digipin',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
