# Generated by Django 5.2.3 on 2025-07-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_digipin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='digipin',
        ),
    ]
