# Generated by Django 5.2.3 on 2025-07-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_address_digipin'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='digipin_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
