# Generated by Django 5.2.3 on 2025-07-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_digipin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='digipin_code',
        ),
        migrations.AddField(
            model_name='address',
            name='digipin',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='India Post DigiPIN'),
        ),
    ]
