# Generated by Django 5.2.3 on 2025-07-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_address_digipin_code_address_digipin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='digipin',
        ),
    ]
