# Generated by Django 5.2.3 on 2025-07-15 06:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('accounts', '0001_initial'),
        ('dealer', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_image', models.ImageField(blank=True, default='photos/Profile_Pic.png', upload_to='photos/add_category')),
                ('status', models.CharField(choices=[('INPROGRESS', 'INPROGRESS'), ('ACCEPTED', 'ACCEPTED'), ('CANCEL', 'CANCEL')], default='INPROGRESS', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dealerprofile')),
            ],
            options={
                'verbose_name': 'Add Category',
                'verbose_name_plural': 'Add Categories',
            },
        ),
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar_card', models.FileField(upload_to='documents/aadhar_card', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'])])),
                ('status', models.CharField(choices=[('INPROGRESS', 'INPROGRESS'), ('ACCEPTED', 'ACCEPTED'), ('CANCEL', 'CANCEL')], default='INPROGRESS', max_length=12)),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='documents/Picture', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('OtherDocuments', models.FileField(blank=True, null=True, upload_to='documents/Other_Documents', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('GSTcertificate', models.FileField(blank=True, null=True, upload_to='documents/GST_certificate', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('CompanyPAN', models.FileField(blank=True, null=True, upload_to='documents/Company_PAN', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('CompanyIncopration', models.FileField(blank=True, null=True, upload_to='documents/Company_Incopration', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='GetPincodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode1', models.CharField(blank=True, max_length=6, null=True)),
                ('pincode2', models.CharField(blank=True, max_length=6, null=True)),
                ('pincode3', models.CharField(blank=True, max_length=6, null=True)),
                ('pincode4', models.CharField(blank=True, max_length=6, null=True)),
                ('pincode5', models.CharField(blank=True, max_length=6, null=True)),
                ('pincode6', models.CharField(blank=True, max_length=6, null=True)),
                ('pincode7', models.CharField(blank=True, max_length=6, null=True)),
                ('pincode8', models.CharField(blank=True, max_length=6, null=True)),
                ('pincode9', models.CharField(blank=True, max_length=6, null=True)),
                ('pincode10', models.CharField(blank=True, max_length=6, null=True)),
                ('addrequest', models.CharField(blank=True, max_length=6, null=True)),
                ('no_of_pincodes', models.IntegerField(blank=True, default=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dealerprofile')),
            ],
            options={
                'verbose_name': 'GetPincode',
                'verbose_name_plural': 'GetPincodes',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('category_name', models.CharField(max_length=250)),
                ('subcategory_name', models.CharField(max_length=250)),
                ('subcategory_image', models.ImageField(blank=True, upload_to='photos/SubCategory')),
                ('slug', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('pcs', 'pcs')], max_length=3)),
                ('GST', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('dealer_account_type', models.CharField(default='Kabadi', max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dealerprofile')),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplace')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.subcategory')),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
            },
        ),
    ]
