# Generated by Django 5.2.3 on 2025-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpincodes',
            name='pincode11',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
