# Generated by Django 5.2.3 on 2025-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_wastedonation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='payment_id',
            new_name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
