# Generated by Django 5.2.3 on 2025-07-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_payment_id_donation_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='razorpay_order_id',
            new_name='payment_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='razorpay_payment_id',
        ),
    ]
