# Generated by Django 5.2.3 on 2025-08-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_razorpay_order_id_donation_payment_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
