# Generated by Django 5.2.3 on 2025-07-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('yes_count', models.IntegerField(default=0)),
                ('no_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_system.votes')),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
            },
        ),
    ]
