# Generated by Django 5.2.3 on 2025-07-15 06:43

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='dealer Name')),
                ('mobile', models.CharField(max_length=10, verbose_name='dealer Mobile No.')),
                ('dealing', multiselectfield.db.fields.MultiSelectField(choices=[('Paper', 'Paper'), ('Plastic', 'Plastic'), ('Glass', 'Glass'), ('Metals', 'Metals'), ('E-waste', 'E-waste'), ('Others', 'Others')], max_length=300)),
                ('min_qty', models.IntegerField(verbose_name='Minimum Quantity')),
                ('max_qty', models.IntegerField(verbose_name='Maximum Quantity')),
                ('pincode', models.CharField(max_length=36, verbose_name='dealer Pincode')),
                ('timing', models.CharField(blank=True, max_length=100, null=True, verbose_name='Timing')),
                ('live_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Live Location')),
            ],
        ),
        migrations.CreateModel(
            name='RequestInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('itemName', models.CharField(max_length=50)),
                ('itemPic', models.ImageField(blank=True, upload_to='photos/dealer/RequestInquiry')),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
            ],
        ),
    ]
