# Generated by Django 5.2.3 on 2025-08-16 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='Dealer Email'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='mobile',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be in the format +911234567890', regex='^\\+91\\d{10}$')], verbose_name='Dealer Mobile No.'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Dealer Name'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='pincode',
            field=models.CharField(max_length=36, verbose_name='Dealer Pincode'),
        ),
    ]
