# Generated by Django 5.2.3 on 2025-07-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalpin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
