# Generated by Django 5.2.3 on 2025-07-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalpin', '0002_address_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='digipin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
