# Generated by Django 5.2.3 on 2025-07-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postalpin', '0003_address_digipin_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='DigiPinAddress',
        ),
    ]
