# Generated by Django 5.2.3 on 2025-07-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_address_digipin'),
        ('postalpin', '0004_rename_address_digipinaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digipinaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
    ]
