# Generated by Django 5.2.3 on 2025-07-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
