# Generated by Django 5.2.3 on 2025-08-16 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_address_digipin'),
        ('invoice', '0004_remove_invoiceitem_invoice_delete_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_numbers', models.JSONField()),
                ('total_order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('calculation_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_due_date', models.DateField()),
                ('auto_generated_after_payment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='accounts.dealerprofile')),
            ],
            options={
                'verbose_name': 'Dealer Commission',
                'verbose_name_plural': 'Dealer Commissions',
                'ordering': ['-calculation_date'],
                'unique_together': {('dealer', 'calculation_date')},
            },
        ),
        migrations.CreateModel(
            name='CommissionPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='commission_payments/screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='invoice.dealercommission')),
            ],
        ),
    ]
