# Generated by Django 5.2.3 on 2025-07-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField(blank=True, null=True)),
                ('order_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('order_note', models.CharField(blank=True, max_length=100)),
                ('order_total', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.CharField(choices=[('8am - 1pm', '8am - 1pm'), ('1pm - 6pm', '1pm - 6pm')], default='8am - 1pm', max_length=30)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('dealer_id', models.IntegerField()),
                ('subcategory_name', models.CharField(max_length=250)),
                ('subcategory_image', models.ImageField(blank=True, upload_to='photos/SubCategory')),
                ('GST', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('pcs', 'pcs')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled by Customer', 'Cancelled by Customer'), ('Cancelled by dealer', 'Cancelled by dealer')], default='New', max_length=30)),
                ('price', models.FloatField()),
                ('order_number', models.CharField(default='20220906KT000005', max_length=50)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.cartitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
