# Generated by Django 5.2.3 on 2025-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
