# Generated by Django 5.2.3 on 2025-07-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cart_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_cart_items',
            field=models.IntegerField(default=0),
        ),
    ]
